### ISSUE TITLE
Gboard keyboard can not be used properly in termux

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-app#1539]
**Problem description**
when gboard input method is used with termux, only ascii keyboard can be used.

**Steps to reproduce**
Install google gboard keyboard, and use it with termux

**Expected behavior**

**Additional information**
never worked with any version of termux

* Termux application version:
* Android OS version:
* Device model:

**Comment by trygveaa** [comment]
It works fine for me (and has always worked fine). You need to provide more details.

**Comment by debugrr** [comment]
I also have no issues with Gboard. 
Is it a particular language? 

do you have similar issues with any other keyboard?

Any character examples? or screenshots?

**Comment by snogglethorpe** [comment]
At least for me, Termux forces Gboard into QWERTY mode, and won't let you
switch to another language.

To input other languages, you need to use Termux's "text input view" (swipe
left on the function key bar); in that mode, all Gboard languages work.

This really isn't very difficult, but maybe it's not so obvious to new
users...

**Comment by trygveaa** [comment]
I can switch to other languages/layouts by long pressing the space bar, no matter if the text input view is active or not. It's not forced to qwerty either.

**Comment by SDRausty** [comment]
> only ascii keyboard can be used

There is a keyboard that builds in Termux on device.  It's called [simple-keyboard](https://github.com/rkkr/simple-keyboard) and can be easily built in Termux with [buildAPKs.developers.tools](https://buildapks.github.io/buildAPKs.developers.tools/).  All the languages in the system are available through settings.

**Comment by snogglethorpe** [comment]
> I can switch to other languages/layouts by long pressing the space bar, no matter if the text input view is active or not. It's not forced to qwerty either.

I wonder if this is Android-version specific.... I'm on Android 7.0.

**Comment by trygveaa** [comment]
Could be. I'm on Android 10 on a Pixel 3.

**Comment by atharvadnaik** [comment]
My problem solved when I switched to different keyboard which doesn't have features like autocorrect, autocomplete or predictive text...You can try turning off predictive text

**Comment by Yisus7u7** [comment]
Simply turn off automatic remediation and autocomplete, or use another keyboard as keyboard hackers

**Comment by YanceyChiew** [comment]
My experience is the same, and turning off spell check and input prediction will not help.

Changing the input method can certainly work, but the premise is that the design of the input method itself does not meet the specifications.

Termux's code is programmed to use a visible password keyboard for regular input, inorder to limit the input character set in the ASCII range, which did not actually works as expected.

Obviously, the password keyboard in gboard will not display any extra buttons, such as settings, clipboard, character selection, etc.

https://github.com/termux/termux-app/blob/d736b1eba5608924080021a236255ba731892016/terminal-view/src/main/java/com/termux/view/TerminalView.java#L269

**Comment by xeffyr** [comment]
@YanceyChiew When using gboard, the input type set as
```
outAttrs.inputType = InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD | InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS; 
```
may cause keyboard to overlap the extra keys row on some configurations.

Before:
![Screenshot_20210602-232307](https://user-images.githubusercontent.com/25881154/120547368-afe18e80-c3f9-11eb-9212-0414d8449053.png)

After:
![Screenshot_20210602-232323](https://user-images.githubusercontent.com/25881154/120547407-bcfe7d80-c3f9-11eb-912d-74bdd066b393.png)

**Comment by agnostic-apollo** [comment]
>may cause keyboard to overlap the extra keys row on some configurations.

Seems like a bug in the rom, android handles pushing up the view itself. It's done by [`WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE`](https://github.com/termux/termux-app/blob/v0.113/termux-shared/src/main/java/com/termux/shared/view/KeyboardUtils.java#L105) flag which is set by [Termux](https://github.com/termux/termux-app/blob/v0.113/app/src/main/java/com/termux/app/terminal/TermuxTerminalViewClient.java#L441). Although, the flag is deprecated in API 30, but it still should work properly, maybe using `WindowInset` API fixes the issue. What's the android version? Working fine on my LG G5  Android `7.0`, also language switching works.

**Comment by xeffyr** [comment]
> What's the android version?

Android 11 from Pixel 5.

**Comment by agnostic-apollo** [comment]
Thanks. Will look into in future. Working fine on pixel 3a android 11 avd though.

**Comment by xeffyr** [comment]
@agnostic-apollo Do you have the latest gboard installed and clipboard suggestions enabled?

**Comment by agnostic-apollo** [comment]
Well, I was on the preinstalled version `9.4.11.312687073-preload-x86`, but I updated to latest version `10.5.03.367007960-release-x86`. I did enable clipboard suggestions but working fine still, but that shouldn't affect hiding of extra keys since suggestions don't show in terminal view, with and without `ctrl-space-workaround` enabled. That's only for input text view, in which extra keys don't show anyways. And "few lines of command prompt" are also not overlapped if extra keys are disabled.

**Comment by RalfWerner** [comment]
I have the same behavior on my Android 9 Gigaset (same Gboard version like @xeffyr but armv7). The _**one**_ Extra Key line (shot1) contains Ctrl (`^`) and `KEYBOARD`-toggle. After _Copy_ the selected text is displayed _over_ the Extra Key line (shot2). Toggling is no longer possible only after back key (shot3). However, the line remains after _again "On-Toggle"_.
The `CRTL+Space` workaround does not work because `^` is hidden. But there are other workarounds such as Hacker/Gboard toggle. Paste removes the clipboard info but _not the line_. In the gboard settings I have found _**no**_ `clipboard line=off` or similar. But possibly have you @agnostic-apollo more success (I prefer Clipboard _in mind_ instaed _on screen_).
![grafik](https://user-images.githubusercontent.com/45426380/120774442-938d4100-c522-11eb-85dc-e81b9ce36a6c.png)
With most of your last changes, I am very satisfied, except for a few workarounds that [remained ff](https://github.com/termux/termux-app/issues/1995#issuecomment-841668368). In the meantime, the "Discord kids" have also discovered "T: X11" and are increasingly changing from VNC to this Xserver. Therefore again the request about _common Extra Keys_.

**Comment by agnostic-apollo** [comment]
So I did some more testing. On Android 11 avd, the clipboard suggestion bar don't show when text is copied with `ctrl-space-workaround=true` and its setting enabled in gboard setttings. It does show on Android 7 LG G5.

This seems like an OS bug to me, android is responsible for pushing up the view depending on keyboard height. In my `logcat`, when clipboard suggestions bar is showing or not, for both cases, the following entries exist, when keyboard is opened

```

I/KeyboardViewUtil: KeyboardViewUtil.getKeyboardHeightRatio():166 systemKeyboardHeightRatio:1.000000; userKeyboardHeightRatio:1.000000.
I/KeyboardViewUtil: KeyboardViewUtil.calculateMaxKeyboardBodyHeight():62 leave 500 height for app when screen height:2392, header height:176 and isFullscreenMode:false, so the max keyboard body height is:1716
I/KeyboardViewUtil: KeyboardViewUtil.calculateMaxKeyboardBodyHeight():62 leave 500 height for app when screen height:2392, header height:176 and isFullscreenMode:false, so the max keyboard body height is:1716
I/NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():114 currentPrimeKeyboardType:SOFT systemPaddingBottom:-1
I/NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():114 currentPrimeKeyboardType:SOFT systemPaddingBottom:-1
```

So android itself is not detecting that gboard suggestions bar is showing. Someone emailed similar case for SwiftKey where number row was covering terminal.

![swiftkey](https://user-images.githubusercontent.com/31106828/120909330-7628b600-c68d-11eb-9a90-2354e62d0c22.jpg)

There is a similar report about this [here](https://stackoverflow.com/questions/66761661), but extra keys work differently.

The hack that I can think of to make this work could to be to allow user to add `terminal-bottom-margin` to `termux.properties` which will be used to always show some space below extra keys and terminal. I guess a key could be added to extra keys to toggle this, so that user for whom this only happens when copying text can do it temporarily while gboard shows the suggestion, and toggle it again when it doesn't. I currently hardcoded this by adding `android:layout_marginBottom="40dp"` to root `RelativeLayout` of [`activity_termux.xml`](https://github.com/termux/termux-app/blob/v0.113/app/src/main/res/layout/activity_termux.xml), but this should be configurable dynamically. Maybe there is a better way, android views are not my thing.

![no-suggestions](https://user-images.githubusercontent.com/31106828/120909335-7f198780-c68d-11eb-9aba-08a55ef2a4d0.png)
![with-suggestions](https://user-images.githubusercontent.com/31106828/120909337-80e34b00-c68d-11eb-9290-a8deab0afbd5.png)

**Comment by RalfWerner** [comment]
> So I did some more testing. On Android 11 avd, the clipboard suggestion bar **don't show** when text is copied

Dit you do version 10.5.03.367007960-release-x86` update?
I did it here on a Pixel-4 AVD with Android 10 and then **get** the overlapping extra row (after _Copy_ [above](https://github.com/termux/termux-app/issues/1539#issuecomment-854496076)):
![grafik](https://user-images.githubusercontent.com/45426380/120915451-f6f2ac80-c6a3-11eb-9610-bb9aae638820.png)

After _Paste_, `BACK` and `KEYBOARD` key I get:
![grafik](https://user-images.githubusercontent.com/45426380/120915504-594bad00-c6a4-11eb-9104-1a22d26b7103.png)

Before of _Paste_ I have replaced clipboard with an alternative text. The workaround has corrected (remove extra line) this again. However, sometimes I get _google_ Restarts or `KEYBOARD` must press several times.
The clipboard text in the extra line is sometimes changed and sometimes not. The _property:_ `enforce-char-based-input=false` _does **not**_ change the behavior. The option "Turn off the Extra line without replacement" (hold in mind) would like me.

**Comment by agnostic-apollo** [comment]
So Gboard issue should be fixed with e7dd0eee. I have tested it on android 7 device, android 10 and 11 avd. For android 11 avd, I had to clear Gboard's app data for new UI to load properly. Moreover, for bug to occur, you also need to enable number keys row toggle to be enabled in gboard settings in addition to clipboard suggestions toggle.

I am not sure if this will fix issues with other keyboards, but hopefully should do it since solution used is kinda generic and will work with and without `enforce-char-based-input` enabled. If this causes some problems, like infinite loop or something of margin adjustments, let me know. Redraws of terminal view are expected in some cases. Check [TermuxActivityRootView javadocs](https://github.com/termux/termux-app/commit/e7dd0eeebe98aaf41a31944e0b6eb62d5f4db8bf#diff-b16f4e311d2a0624fb245c34e1f03b627bb96b9440a57f400b2818e212deb941R21) for the details. It also clears some inaccuracies in my above comment.

New release is planned to be released today if no bugs come in.

**Comment by RalfWerner** [comment]
Thanks! I've checked on my `Pixel_2_API_30.avd`. Complete reset was needet (stalled 2 h work/wait) and gboard update. I get:
![grafik](https://user-images.githubusercontent.com/45426380/121507320-d2207100-c9e4-11eb-8e82-27c868c650c2.png)

Aditional to this (arch=i686) I've installed on my Gigaset (arch=arm) and get:
![grafik](https://user-images.githubusercontent.com/45426380/121508058-815d4800-c9e5-11eb-8ceb-a03a51a2cdd3.png)
On both devices your last _master update_ (version 114 I've extendet) are installed and the [boot-loop](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-780625381) update was done. I continue with [OS-KB](https://github.com/termux/termux-app/pull/2114#issuecomment-855899147) check. The _gboard_ bug is solved and this issue _**could be closed!**_

**Comment by agnostic-apollo** [comment]
Thanks for the confirmation. Would be good to have swiftkey number rows solved as well.

> The gboard bug is solved and this issue could be closed!

This issue is not related to overlap issue. Overlap is (also) reported in #538

**Comment by RalfWerner** [comment]
> Would be good to have swiftkey number rows solved as well.

If [above](https://github.com/termux/termux-app/issues/1539#issuecomment-855319180) the extra key line is _missing_, the problem is already solved in v113. In the following shot (horizontal split), next to the Swift-KB, Termux (left) _with_ the Extra Key line and X11 (right) _with its Extra Keys (not in vertical position) can be seen - _without overlaps._
![grafik](https://user-images.githubusercontent.com/45426380/121521285-2da62b00-c9f4-11eb-90b1-8270c27a90e6.png)

**Comment by agnostic-apollo** [comment]
It could also be a device specific issue so not sure yet. And e7dd0ee should work even if extra keys are enabled or not.

**Comment by lctx** [comment]
This bug appears me  after type "apt upgrade" using the app from Google Play(is not the last version), so I uninstall it and install the Fdroid version 0.117 but the bug still persist.
I solve this changing the idiom of gboard from multilingual(English / Spanish) to Spanish or English.
I'm using a Redmi C3 and use Android 11.

**Comment by agnostic-apollo** [comment]
So I managed to reproduce the issue too. It doesn't happen in all multilingual languages including Norwegian.

It does happen with Chinese Traditional language, when you open termux with it selected, the keyboard space bars literally says `QWERTY` instead of the Chinese language symbols. The value for `enforce-char-based-input` does not affect this, so I wonder how chinese people type passwords in chinese if gboard switches to `QWERTY` mode with `InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD | InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS`. The value for `Suggest English words` which would likely be equivalent to `Multilingual typing` toggle for some other languages does not affect it either. I only tested on Android 7 though.

Also found a termux bug where if in text input view mode and chinese was showing properly and I switch to another app and come back to termux which would still start in text input view mode, the `QWERTY` keyboard was loaded. That should be fixed by 2b7aa5e.

As for fixing the forced `QWERTY` issue, that seems to be an issue with Gboard and not termux, although chinese does show with `InputType.TYPE_TEXT_VARIATION_URI` but that has the issue of characters not showing until space is pressed. It should be reported to Gboard support for fixing since we need correct behaviour with `InputType.TYPE_NULL`.

![Gboard](https://user-images.githubusercontent.com/31106828/127555748-2ee2ec43-138d-459b-8eb1-430e6a6d1465.jpg)
![Terminal-View](https://user-images.githubusercontent.com/31106828/127555773-596306ea-cb62-4dbd-8910-f1ac63229854.jpg)
![Text-Input-View](https://user-images.githubusercontent.com/31106828/127555777-e4e38828-dfb1-4140-8a2b-24383dc9daa6.jpg)

**Comment by plusls** [comment]
any progress?
