### ISSUE TITLE
[Bug]: Can't Change the wallpaper on xfce4 native.

### ISSUE THREAD

**Issue by Phinixprono123** [termux/termux-app#4324]
### Problem description

So I recently reinstalled termux because I have an bad habit of reinstalling and uninstalling it. And updted the packages correctly. Everything was going alright I installed xfce4 termux x11 app to run xfce4 on there. Then when I launched it I saw an new walaper was on the screen so I knew this must be an update. I decided to change the wallpaper because I like to change to custom wallpapers. But I couldn't. I tried clicking hard, refreshing, asking some people. But no good. I also tried redoing everything because I thought I may have done something incorrectly. But still same results. I think this is because of some new update of the xfce4 desktop package but idk sure though. Anyways please fix this as soon as possible. And also it glitches.

### Steps to reproduce the behavior.

termux-setup-storage
pkg update -y
pkg upgrade -y
pkg install git wget -y
pkg install x11-repo -y
pkg install termux-x11-nightly -y
pkg install xfce4 xfce4-terminal xfce4-whiskermenu-plugin -y
termux-x11 :0 -xstartup startxfce4

I used the -legacy-drawing thing because I have an older android.

Then go to the x11 app and try to change the walapaper.

### What is the expected behavior?

The expected behavior is that it would let em change the wallpaper and not be glitchy.

### System information

* Termux application version: 0.118.1
* Android OS version: 8.1
* Device model: vivo y85

**Comment by RalfWerner** [comment]
I don't use **XFCE4** but maybe your problem was solved with the latest [X11.apk](https://github.com/termux/termux-x11/actions/runs/12476603692#artifacts) (1.03.01-0d58c0e-24.12.24)? With **fluxbox** and the latest package _and artifact_ updates I can change the background.

**Comment by Phinixprono123** [comment]
> I don't use **XFCE4** but maybe your problem was solved with the latest [X11.apk](https://github.com/termux/termux-x11/actions/runs/12476603692#artifacts) (1.03.01-0d58c0e-24.12.24)? With **fluxbox** and the latest package _and artifact_ updates I can change the background.

Nope still not fixed the xfce4 problem yet plus it has more bugs and glitches than expected after I researched more. And after it got Installed it also gives some warnings and stuff. I ho eit gets fixed soon

**Comment by RalfWerner** [comment]
sad that you still have **xfce4** problems. I recommend describing them using simple examples that can be repeated by the developer (action->effect). You could also check alternatives like **fluxbox** as a simple Windows/desktop manager to rule out problems outside of **xfce4**.

**Comment by Poko-Cmnt** [comment]
Same issue here, can't change wallpaper on termux native xfce4.

Termux version: 0.118.1
Termux:X11 version: 1.03.01-4427cf4-05.01.25
OS: Android 13

**Comment by 813ethan** [comment]
try if this pr works for you
https://github.com/termux/termux-packages/pull/22654

**Comment by Poko-Cmnt** [comment]
> try if this pr works for you [termux/termux-packages#22654](https://github.com/termux/termux-packages/pull/22654)

It did work, now i can change the wallpaper. thanks for the hard work.

**Comment by twaik** [comment]
Merged.
